let questions = [
    {
      numb: 1,
      category: "quiz",
      type: "multiple",
      difficulty: "level1",
      question: "Qual tipo de rede permite que computadores em um escritório ou em casa o conectem a uma rede corporativa?",
      answer: "rede SOHO  ",
      options: [
        "redes médias a grandes",
        "rede mundial",
        "rede SOHO",
        "rede doméstica inteligente",
      ],
    },
    {
      numb: 2,
      category: "quiz",
      type: "multiple",
      level: 1,
      text: "O que pode ser colocado dentro ou sobre um pacote para que ele possa ser rastreado?",
      answer: "tag de RFID",
      options: [
        "tag de RFID",
        "placa de interface de Rede",
        "um atuador",
        "sensor",
      ],
      feedback_correct:"parabens!",
      feedback_incorreck:"você errou!",
    },
   {
      numb: 3,
      category: "quiz",
      type: "multiple",
      difficulty: "level1",
      question: "Uma unidade básica de informação que representa um dos dois estados distintos é conhecida como:",
      answer: "bit",
      options: [
        "byte",
        "bit",
        "sinal elétrico",
        "octeto",
      ],
    },
   {
      numb: 4,
      category: "quiz",
      type: "multiple",
      difficulty: "level1",
      question: "Ao usar o cartão de crédito para fazer compras em vários locais, a empresa do cartão de crédito pode usar essas informações para saber mais sobre sua localização e suas preferências. Esse tipo de dados pessoais é conhecido como:",
      answer: "dados inferidos",
      options: [
        "dados observados",
        "dados secretos",
        "dados inferidos",
        "dados voluntários",
      ],
    },
  {
      numb: 5,
      category: "quiz",
      type: "multiple",
      difficulty: "level1",
      question: "Qual dos seguintes métodos de transmissão de sinal usa frequências ou pulsos de luz?",
      answer: "sinais ópticos",
      options: [
        "sinais elétricos",
        "sinais sem fio",
        "sinais ópticos",
      ],
    },
  {
      numb: 6,
      category: "quiz",
      type: "multiple",
      difficulty: "level1",
      question: "A capacidade de um meio físico transportar dados é conhecida como:",
      answer: "largura de banda",
      options: [
        "taxa de dados",
        "largura de banda",
        "taxa de transferência",
        "velocidade",
      ],
    },
    {
      numb: 7,
      category: "quiz",
      type: "multiple",
      difficulty: "level1",
      question: "Qual das seguintes medições inclui qualquer latência encontrada durante as transmissões de dados?",
      answer: "taxa de transferência",
      options: [
        "largura de banda",
        "taxa de transferência",
        "velocidade",
        "taxa de dados",
      ],
    },
    {
      numb: 8,
      category: "quiz",
      type: "multiple",
      difficulty: "level1",
      question: "Qual das seguintes medições inclui qualquer latência encontrada durante as transmissões de dados?",
      answer: "bits por segundo",
      options: [
        "bits por milissegundo",
        "número total de bits",
        "bytes por milissegundo",
        "bits por segundo",
        "bytes por segundo",
      ],
    },
];
